services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096
    volumes:
      - ./configs/jellyfin:/config
      - /mnt/nas_media:/media:ro
    restart: unless-stopped

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PORT=45876
      - KEY=${BESZEL_KEY}
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ./configs/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
